In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('D:/NCTU/12-資料產出/NCTU/alert處理new3.csv')
df

,alert_id,run_date,primary_entity_level_code,primary_entity_number,scenario_name,TO_SAR,Acct_No,Cust_No,Cust_Key,Cust_Segmentation,...,Extnl_Cust_Ind,Negative_News_Ind,Prim_Br_No,Obu_Ind,Riskclass_Cd,risk_score,last_risk_assessment_date,change_current_ind,change_begin_date,change_end_date
0,14481254,2019/3/4,ACC,FP-116007004049,TWN_A17_01,NaN,FP-116007004049,>.-.1/67;4,63163503,PH,...,N,N,116.0,N,3.0,315.18,2018/11/30,N,2018/12/14,2019/5/5 23:59
1,14481255,2019/3/4,ACC,PB-016008286512,TWN_A17_01,NaN,PB-016008286512,I.//467433,68099071,PNH,...,N,N,16.0,N,2.0,113.68,2018/11/23,N,2018/12/28,2019/3/28 23:59
2,14481256,2019/3/4,ACC,PB-025008428448,TWN_A17_01,NF,PB-025008428448,>+/250396<,63137042,PH,...,N,N,25.0,N,3.0,308.93,2018/11/30,N,2018/12/14,2019/3/7 23:59
3,14481257,2019/3/4,ACC,PB-026008470094,TWN_A17_01,NaN,PB-026008470094,C+/2227157,64347661,PNH,...,N,N,26.0,N,2.0,114.09,2018/11/30,N,2018/12/14,2019/5/1 23:59
4,14481258,2019/3/4,ACC,PB-027008462525,TWN_A17_01,NaN,PB-027008462525,A+/-032674,69939509,PNH,...,N,N,27.0,N,1.0,0.00,2019/2/23,N,2019/2/23,2019/3/31 23:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347671,16581234,2020/12/31,ACC,PB-141004130992,TWN_A15_01,NaN,PB-141004130992,=+/0.304:7,108579829,PNH,...,N,N,55.0,N,1.0,53.00,2020/12/31,Y,2020/12/31,5999/1/1 00:00
347672,16581235,2020/12/31,ACC,PB-146004080681,TWN_A15_01,NaN,PB-146004080681,L./0.79846,107244141,PNH,...,N,N,146.0,N,1.0,90.34,2020/6/18,Y,2020/12/4,5999/1/1 00:00
347673,16581237,2020/12/31,ACC,PB-241004057317,TWN_A15_01,NaN,PB-241004057317,I+/0.57359,105111174,PNH,...,N,N,241.0,N,1.0,62.43,2018/11/30,Y,2020/12/4,5999/1/1 00:00
347674,16581238,2020/12/31,ACC,PB-246004317763,TWN_A15_01,NaN,PB-246004317763,A+/1241355,102039956,PNH,...,N,N,26.0,N,1.0,90.34,2020/3/30,Y,2020/12/4,5999/1/1 00:00
347675,16581239,2020/12/31,ACC,PB-271004088092,TWN_A15_01,NaN,PB-271004088092,?+--04424;,100901441,PNH,...,N,N,271.0,N,1.0,62.43,2019/3/5,Y,2020/12/4,5999/1/1 00:00

In [4]:
df['TO_SAR'] = df['TO_SAR'].replace(np.nan, 0)
df['TO_SAR'] = df['TO_SAR'].replace('F', 1)
df['TO_SAR'] = df['TO_SAR'].replace('NF', 1)

df['TO_SAR'].value_counts()

0    346736
1       940
Name: TO_SAR, dtype: int64

In [5]:
df['scenario_name'].value_counts()

TWN_A1B_01    90059
TWN_A11_01    86770
TWN_A12_01    49965
TWN_A21_02    33812
TWN_A21_01    26202
TWN_A21_03    13059
TWN_A15_01    12530
TWN_A13_01     7499
TWN_A17_01     4507
TWN_A1C_01     3700
TWN_AB4_01     3288
BOT_AZ2_01     2984
TWN_AB2_01     2622
TWN_A1A_01     1984
TWN_A61_01     1982
BOT_AZ8_01     1104
TWN_AB3_01     1016
TWN_A1F_01      802
TWN_A81_01      723
BOT_AZ1_01      617
TWN_A1D_01      604
TWN_A18_01      440
TWN_AB1_01      383
TWN_A62_01      211
TWN_T35_01      205
BOT_AZ9_01      166
TWN_AA3_01       87
TWN_D14_01       83
TWN_AB3_02       70
TWN_A21_04       44
BOT_DX1_01       44
TWN_A16_01       36
BOT_AZ5_01       22
TWN_AA2_02       21
TWN_A1B_02       16
BOT_DX2_01       11
TWN_A81_02        3
TWN_T18_01        2
TWN_AA2_01        1
TWN_T14_01        1
BOT_AZ3_01        1
Name: scenario_name, dtype: int64

In [6]:
df['run_date'] = pd.to_datetime(df['run_date'].copy())
df['month'] = df['run_date'].dt.month
df['day'] = df['run_date'].dt.day

In [7]:
TO_SAR = df[df['TO_SAR']!= 0]
Non_SAR = df[df['TO_SAR'] == 0]
print(f'total shape:{df.shape}')
print(f'TO_SAR shape:{TO_SAR.shape}, Non_SAR shape:{Non_SAR.shape}')

total shape:(347676, 43)
TO_SAR shape:(940, 43), Non_SAR shape:(346736, 43)

In [10]:
Non_SAR.columns

Index(['alert_id', 'run_date', 'primary_entity_level_code',
       'primary_entity_number', 'scenario_name', 'TO_SAR', 'Acct_No',
       'Cust_No', 'Cust_Key', 'Cust_Segmentation', 'Cust_Typ_Cd', 'Cust_Id_Id',
       'Cust_Id_Typ_Desc', 'Cust_Id_State_Cd', 'Cust_Dt_Of_Birth',
       'Cust_Sts_Desc', 'Street_Postal_Cd', 'Street_Cntry_Cd',
       'Mailing_Postal_Cd', 'Mailing_Cntry_Cd', 'Residence_Cntry_Cd',
       'Citizenship_Cntry_Cd', 'Org_Cntry_Of_Buz_Cd', 'Empl_No', 'Ocup_Code',
       'job_title_code', 'Lst_Cont_Dt', 'Politically_Exposed_Pers_Ind',
       'Non_Prft_Org_Ind', 'Cust_Since_Dt', 'Lst_Susp_Actv_Rpt_Dt',
       'Extnl_Cust_Ind', 'Negative_News_Ind', 'Prim_Br_No', 'Obu_Ind',
       'Riskclass_Cd', 'risk_score', 'last_risk_assessment_date',
       'change_current_ind', 'change_begin_date', 'change_end_date', 'month',
       'day'],
      dtype='object')

In [11]:
plt.figure()
Non_SAR.groupby('month').count